// <auto-generated />
using System;
using AdminLTE.MVC.Data;
using EntityFrameworkCore.Jet.Metadata;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdminLTE.MVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250220221908_access2")]
    partial class access2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AdminLTE.MVC.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longchar");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("longchar");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("smallint");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("longchar");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("longchar");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longchar");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longchar");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("longbinary");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longchar");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("smallint");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("longchar");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("IGNORE NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("AdminLTE.MVC.Models.Matiere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("longchar");

                    b.HasKey("Id");

                    b.ToTable("Matieres");
                });

            modelBuilder.Entity("AdminLTE.MVC.Models.Phase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.HasKey("Id");

                    b.ToTable("Phases");
                });

            modelBuilder.Entity("AdminLTE.MVC.Models.Specialite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT(100)");

                    b.HasKey("Id");

                    b.ToTable("Specialites");
                });

            modelBuilder.Entity("AdminLTE.MVC.Models.Stage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("longchar");

                    b.Property<string>("Promotion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("longchar");

                    b.HasKey("Id");

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("AdminLTE.MVC.Models.StagePhase", b =>
                {
                    b.Property<long>("StageId")
                        .HasColumnType("integer");

                    b.Property<long>("PhaseId")
                        .HasColumnType("integer");

                    b.Property<long>("SpecialileId")
                        .HasColumnType("integer");

                    b.Property<string>("AddedOn")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("DateDebut")
                        .HasColumnType("longchar");

                    b.Property<string>("DateFin")
                        .HasColumnType("longchar");

                    b.HasKey("StageId", "PhaseId", "SpecialileId");

                    b.HasIndex("SpecialileId");

                    b.HasIndex(new[] { "PhaseId" }, "IX_StagePhases_PhaseId");

                    b.ToTable("StagePhases");
                });

            modelBuilder.Entity("AdminLTE.MVC.Models.Stagiaire", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Branche")
                        .HasColumnType("longchar");

                    b.Property<string>("Cin")
                        .HasColumnType("longchar");

                    b.Property<string>("Grade")
                        .HasColumnType("longchar");

                    b.Property<string>("Mle")
                        .HasColumnType("longchar");

                    b.Property<string>("Nom")
                        .HasColumnType("longchar");

                    b.Property<string>("NomAr")
                        .HasColumnType("longchar");

                    b.Property<string>("Prenom")
                        .HasColumnType("longchar");

                    b.Property<string>("PrenomAr")
                        .HasColumnType("longchar");

                    b.Property<string>("Promotion")
                        .HasColumnType("longchar");

                    b.Property<long?>("SpecialiteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpecialiteId");

                    b.ToTable("Stagiaires");
                });

            modelBuilder.Entity("AdminLTE.MVC.Models.StagiaireStage", b =>
                {
                    b.Property<long>("StagiaireId")
                        .HasColumnType("integer");

                    b.Property<long>("StageId")
                        .HasColumnType("integer");

                    b.Property<long>("SpecialiteId")
                        .HasColumnType("integer");

                    b.Property<string>("DateDebut")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("DateFin")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.HasKey("StagiaireId", "StageId", "SpecialiteId");

                    b.HasIndex("SpecialiteId");

                    b.ToTable("StagiaireStages");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longchar");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("longchar");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("longchar");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("IGNORE NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("longchar");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longchar");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("longchar");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longchar");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longchar");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longchar");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("AdminLTE.MVC.Models.StagePhase", b =>
                {
                    b.HasOne("AdminLTE.MVC.Models.Phase", "Phase")
                        .WithMany("StagePhases")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminLTE.MVC.Models.Specialite", "Specialile")
                        .WithMany("StagePhases")
                        .HasForeignKey("SpecialileId")
                        .IsRequired();

                    b.HasOne("AdminLTE.MVC.Models.Stage", "Stage")
                        .WithMany("StagePhases")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phase");

                    b.Navigation("Specialile");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("AdminLTE.MVC.Models.Stagiaire", b =>
                {
                    b.HasOne("AdminLTE.MVC.Models.Specialite", "Specialite")
                        .WithMany("Stagiaires")
                        .HasForeignKey("SpecialiteId");

                    b.Navigation("Specialite");
                });

            modelBuilder.Entity("AdminLTE.MVC.Models.StagiaireStage", b =>
                {
                    b.HasOne("AdminLTE.MVC.Models.Specialite", "Specialite")
                        .WithMany("StagiaireStages")
                        .HasForeignKey("SpecialiteId")
                        .IsRequired();

                    b.HasOne("AdminLTE.MVC.Models.Stagiaire", "Stagiaire")
                        .WithMany("StagiaireStages")
                        .HasForeignKey("StagiaireId")
                        .IsRequired();

                    b.Navigation("Specialite");

                    b.Navigation("Stagiaire");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AdminLTE.MVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AdminLTE.MVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminLTE.MVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AdminLTE.MVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdminLTE.MVC.Models.Phase", b =>
                {
                    b.Navigation("StagePhases");
                });

            modelBuilder.Entity("AdminLTE.MVC.Models.Specialite", b =>
                {
                    b.Navigation("StagePhases");

                    b.Navigation("StagiaireStages");

                    b.Navigation("Stagiaires");
                });

            modelBuilder.Entity("AdminLTE.MVC.Models.Stage", b =>
                {
                    b.Navigation("StagePhases");
                });

            modelBuilder.Entity("AdminLTE.MVC.Models.Stagiaire", b =>
                {
                    b.Navigation("StagiaireStages");
                });
#pragma warning restore 612, 618
        }
    }
}
